# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "*.md"
      type: "docs"
    values:
      layout: "page"

# Site settings
title: AI-DC
description: AI-powered data center transformation
baseurl: "/ai-dc"
url: "https://jimmcguffinus.github.io"
permalink: pretty

# Theme settings
theme: minima
minima:
  date_format: "%b %-d, %Y"
  social_links:
    github: jimmcguffinus

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links

show_excerpts: true
relative_links:
  enabled: true
  collections: true

# Navigation
header_pages:
  - about.md
  - documentation.md
  - components.md

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .gitignore

# Additional settings
future: true
encoding: UTF-8
sass:
  style: compressed 