site_name: AI-DC Documentation
site_description: Documentation for AI-DC project
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight

nav:
  - Home: index.md
  - Documentation:
    - Overview: Readme_AD-YOLO.md
    - Getting Started:
      - Company Overview: 01_Company_Breakdown.md
      - AI Strategy: 02_AI_Strategy.md
      - Implementation Plan: 03_Implementation_Plan.md
    - Core Components:
      - Vector DB Setup: 08_VectorDB_Setup.md
      - AD-YOLO Core: 31_AD_YOLO_Vector_DB_RAG_AI.md
      - Schema Extension: 32_AD_YOLO_Schema_Extension_AuxLogin.md
      - Firewall Sync: 33_AD_YOLO_AD_Firewall_Sync.md
      - Real-Time Monitoring: 28_AD_YOLO_Real_Time_AD_Monitoring.md
      - Firebase Integration: 29_AD_YOLO_Firebase_Sync.md
      - Ticketing Integration: 30_AD_YOLO_Ticketing_Helpdesk_Integration.md
    - Implementation:
      - Phase 1 - Network: 04_Phase1_Network_AI.md
      - Phase 2 - Colocation: 05_Phase2_Colo_AI.md
      - Phase 3 - Cloud: 06_Phase3_Cloud_AI.md
      - Phase 4 - Security: 07_Phase4_Security_AI.md
    - Services:
      - Network Cabling: 11_Network_Cabling_Company_AI.md
      - VoIP Services: 12_VoIP_Phone_Service_AI.md
      - Video Surveillance: 13_Video_Surveillance_AI.md
      - Best Practices: 14_Best_Practices_AI_Datacenter.md
  - Business:
    - Development: 15_Business_Development_AI.md
    - Network Automation: 16_Network_Automation_AI.md
    - AI Automation: 17_Business_AI_Automation.md
    - Training & R&D: 18_AI_Training_and_RnD.md
    - Colocation: 19_Colocation_Hosting_AI.md
    - Internet Services: 20_Business_Internet_AI.md
    - Network Security: 21_AI_Network_Security.md
  - Market Analysis:
    - Research & Development: 22_AI_Research_Development_AI_Markets_Growth.md
    - Smart Technology: 23_Autonomous_Smart_Tech_AI_Markets_Growth.md
    - Healthcare & Biotech: 24_Healthcare_Biotech_AI_Markets_Growth.md
    - Enterprise Automation: 25_Enterprise_Business_Automation_AI_Markets_Growth.md
    - Government & Defense: 26_Government_Defense_AI_Markets_Growth.md
  - Resources:
    - Future Vision: 27_AI_Datacenter_Future_Vision.md
    - Organization Chart: Future_DataCenter_OrgChart_AI.md
    - About: about.md

plugins:
  - search
  - tags

markdown_extensions:
  - tables
  - attr_list
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
